name: Advent Of Code Tests

on: 
    push: 

jobs: 
    test: 
        name: Test solutions
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - uses: gradle/wrapper-validation-action@v1
            - uses: actions/setup-java@v4
              with: 
                  distribution: 'temurin'
                  java-version: '17'
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
              with: 
                  arguments: test
                  